// NOTE: The `.open-next/worker.js` import is generated by the build step.
// Run `npx open-next build` (or your build script) before deploying.
// This file does not exist until the build has completed.
//
// Cloudflare Workers Analytics / Tail Logging:
// Use `wrangler tail` to stream live logs during development.
// For production monitoring, enable Workers Analytics Engine:
//   1. Go to Cloudflare Dashboard > Workers & Pages > your worker > Analytics
//   2. Enable "Logs" and/or "Analytics Engine" binding
// To add an Analytics Engine binding, uncomment and configure in wrangler.toml:
//   [analytics_engine_datasets]
//   binding = "LEADROOM_ANALYTICS"
// Then inject via env: env.LEADROOM_ANALYTICS.writeDataPoint({ ... })
import handler from '../.open-next/worker.js';
import { getLogger } from '@/lib/logger';
import { ResearchSnapshotWorkflow } from './workflows/research-snapshot';
import { DiscoverySearchWorkflow } from './workflows/discovery-search';
import { MonitorStalledLeadWorkflow } from './workflows/monitor-stalled-lead';

const log = getLogger('entry');

export default {
  async fetch(request: Request, env: any, ctx: any) {
    if (typeof handler.fetch === 'function') {
      return handler.fetch(request, env, ctx);
    }
    return (handler as any)(request, env, ctx);
  },

  async scheduled(event: ScheduledEvent, env: any, ctx: any) {
    const { getDb } = await import('./db');
    const { runAllSweeps } = await import('./services/sweeps');
    const db = getDb(env);
    const result = await runAllSweeps(db);
    log.info('Sweep run complete', { result: JSON.stringify(result) });
  }
};

export { ResearchSnapshotWorkflow, DiscoverySearchWorkflow, MonitorStalledLeadWorkflow };
